import { ExamDocument, KopHeaderConfig, SchoolType, SignatureConfig } from "@/types/exam";

export const DEFAULT_KOP_SMP: KopHeaderConfig = {
  yayasanName: "YAYASAN ALHAMIDY PRINGSEWU",
  institutionName: "SMP Qur'an Al-Hamidy",
  akreditasi: "TERAKREDITASI A (Unggul Qur'ani)",
  npsnNss: "NPSN: 20531234 | NSS: 202052801001",
  address: "Kompleks Pesantren Al-Hamidy, Pringsewu, Lampung 35373",
  phoneEmail: "Telp/WA: (0729) 211899 | Email: smpquran@alhamidy-pringsewu.sch.id",
  website: "www.alhamidy-pringsewu.sch.id",
  headerLineStyle: "double",
};

export const DEFAULT_KOP_SMA: KopHeaderConfig = {
  yayasanName: "YAYASAN ALHAMIDY PRINGSEWU",
  institutionName: "SMA Plus Al-Hamidy",
  akreditasi: "TERAKREDITASI A (Plus Pesantren)",
  npsnNss: "NPSN: 20535678 | NSS: 302052801002",
  address: "Kompleks Pesantren Al-Hamidy, Pringsewu, Lampung 35373",
  phoneEmail: "Telp/WA: (0729) 211900 | Email: smaplus@alhamidy-pringsewu.sch.id",
  website: "www.alhamidy-pringsewu.sch.id",
  headerLineStyle: "double",
};

export const DEFAULT_SIG_SMP: SignatureConfig = {
  locationDate: "Pringsewu, " + new Date().toLocaleDateString("id-ID", { day: "numeric", month: "long", year: "numeric" }),
  principalTitle: "Kepala SMP Qur'an Al-Hamidy",
  principalName: "Diana Ariyanti, M.Pd.",
  principalNip: "NIY. 19850412 201001 2 002",
  teacherTitle: "Guru Pengampu Mata Pelajaran",
  teacherName: "Ust. M. Ridwan, S.Ag.",
  teacherNip: "NIY. 19900215 201502 1 018",
  showSchoolStamp: true,
  stampText: "YAYASAN ALHAMIDY PRINGSEWU * SMP QUR'AN *",
  qrCodeVerification: true,
  verificationCode: "ALH-SMP-2026-VAL892",
};

export const DEFAULT_SIG_SMA: SignatureConfig = {
  locationDate: "Pringsewu, " + new Date().toLocaleDateString("id-ID", { day: "numeric", month: "long", year: "numeric" }),
  principalTitle: "Kepala SMA Plus Al-Hamidy",
  principalName: "Nur Azizah, M.Pd.",
  principalNip: "NIY. 19780915 200501 2 005",
  teacherTitle: "Guru Pengampu Mata Pelajaran",
  teacherName: "Ustdz. Nur Laila, M.Pd.",
  teacherNip: "NIY. 19920810 201803 2 009",
  showSchoolStamp: true,
  stampText: "YAYASAN ALHAMIDY PRINGSEWU * SMA PLUS *",
  qrCodeVerification: true,
  verificationCode: "ALH-SMA-2026-VAL991",
};

export const SUBJECTS_BY_SCHOOL: Record<SchoolType, { categories: string[]; subjectsByGrade: Record<string, string[]> }> = {
  "SMP Qur'an Al-Hamidy": {
    categories: ["Qur'an & Pesantren", "MIPA & Teknologi", "Bahasa & Sastra", "Sosial & Kewarganegaraan"],
    subjectsByGrade: {
      "Kelas 7": [
        "Tahfizh Al-Qur'an & Tajwid",
        "Pendidikan Agama Islam & Budi Pekerti",
        "Bahasa Arab (Nahu & Shorof Dasar)",
        "Bahasa Indonesia",
        "Bahasa Inggris",
        "Matematika",
        "IPA Terpadu (Fisika & Biologi)",
        "IPS Terpadu",
        "Informatika",
        "Pendidikan Pancasila",
        "Seni Budaya & Prakarya",
        "PJOK",
      ],
      "Kelas 8": [
        "Tahfizh Al-Qur'an & Tajwid",
        "PAI & Aqidah Akhlak",
        "Bahasa Arab",
        "Bahasa Indonesia",
        "Bahasa Inggris",
        "Matematika",
        "IPA Terpadu",
        "IPS Terpadu",
        "Informatika",
        "Pendidikan Pancasila",
        "Seni Budaya",
        "PJOK",
      ],
      "Kelas 9": [
        "Tahfizh Al-Qur'an & Ujian Syahadah",
        "PAI & Fiqih/Ilmu Tafsir",
        "Bahasa Arab & Kitab Kuning",
        "Bahasa Indonesia",
        "Bahasa Inggris",
        "Matematika",
        "IPA Terpadu",
        "IPS Terpadu",
        "Informatika",
        "Pendidikan Pancasila",
      ],
    },
  },
  "SMA Plus Al-Hamidy": {
    categories: ["Qur'an & Keislaman", "Sains & Matematika", "Sosial & Ekonomi", "Bahasa & Humaniora"],
    subjectsByGrade: {
      "Kelas 10": [
        "Tahfizh Al-Qur'an & Tajwid Praktis",
        "PAI & Al-Qur'an Hadits",
        "Bahasa Arab Lanjutan",
        "Matematika Umum",
        "Fisika (Fase E)",
        "Kimia (Fase E)",
        "Biologi (Fase E)",
        "Ekonomi & Sosiologi (Fase E)",
        "Geografi & Sejarah (Fase E)",
        "Bahasa Indonesia",
        "Bahasa Inggris",
        "Informatika & AI Dasar",
        "Pancasila",
      ],
      "Kelas 11": [
        "Tahfizh Al-Qur'an & Tafsir Tematik",
        "PAI & Fiqih Muamalah",
        "Bahasa Arab & Balaghoh",
        "Matematika Tingkat Lanjut",
        "Matematika Umum",
        "Fisika (Fase F)",
        "Kimia (Fase F)",
        "Biologi (Fase F)",
        "Ekonomi (Fase F)",
        "Sosiologi (Fase F)",
        "Geografi (Fase F)",
        "Sejarah Indonesia",
        "Bahasa Indonesia",
        "Bahasa Inggris / TOEFL",
        "Informatika",
      ],
      "Kelas 12": [
        "Tahfizh Al-Qur'an & Syahadah 30 Juz",
        "PAI & Ushul Fiqih",
        "Bahasa Arab Lanjutan",
        "Matematika Tingkat Lanjut",
        "Fisika",
        "Kimia",
        "Biologi",
        "Ekonomi",
        "Sosiologi",
        "Geografi",
        "Bahasa Indonesia",
        "Bahasa Inggris",
        "Persiapan SNBT & UTBK",
      ],
    },
  },
};

export const SAMPLE_BANK_SOAL: ExamDocument[] = [
  {
    id: "sample-smp-01",
    title: "Sumatif Tengah Semester (STS) Ganjil - Tahfizh & Tajwid",
    institution: "SMP Qur'an Al-Hamidy",
    grade: "Kelas 7",
    subject: "Tahfizh Al-Qur'an & Tajwid",
    assessmentType: "Summative",
    semester: "Ganjil",
    academicYear: "2025/2026",
    timeLimitMinutes: 90,
    generalInstructions: [
      "Awali pekerjaan dengan membaca Basmalah dan niat ikhlas.",
      "Tuliskan nama lengkap, kelas, dan nomor absen pada lembar jawaban.",
      "Periksa kelengkapan soal sebelum mulai menjawab.",
      "Dilarang bekerjasama dan menggunakan alat bantu dalam bentuk apapun.",
    ],
    summaryCP: "Peserta didik mampu memahami hukum bacaan Nun Sukun/Tanwin, Mim Sukun, Makhraj Huruf, serta menghafal Al-Qur'an Juz 30 sesuai kaidah tajwid.",
    summaryTP: "Menganalisis hukum bacaan Izhar, Idgham, Iqlab, dan Ikhfa' dalam ayat Al-Qur'an serta menerapkannya dalam bacaan.",
    kopConfig: DEFAULT_KOP_SMP,
    sigConfig: DEFAULT_SIG_SMP,
    createdAt: "2026-07-20T08:00:00Z",
    updatedAt: "2026-07-20T08:00:00Z",
    questions: [
      {
        id: "q1",
        number: 1,
        type: "pilihan_ganda",
        stimulus: "Perhatikan firman Allah SWT berikut: ﴿مِنْ بَعْدِ مَا جَاءَتْهُمُ الْبَيِّنَاتُ﴾",
        questionText: "Hukum bacaan tajwid pada lafaz ﴿مِنْ بَعْدِ﴾ yang ditandai Nun Sukun bertemu huruf Ba (ب) adalah...",
        options: [
          "A. Izhar Halqi",
          "B. Idgham Bighunnah",
          "C. Iqlab",
          "D. Ikhfa' Haqiqi",
        ],
        answerKey: "C. Iqlab",
        explanation: "Nun sukun bertemu huruf Ba (ب) dibaca Iqlab, yaitu mengganti suara Nun sukun menjadi Mim sukun disertai dengung (ghunnah).",
        bloomLevel: "C2 (MOTS)",
        cpElement: "Hukum Tajwid Nun Sukun",
        indikatorSoal: "Disajikan potongan ayat, siswa dapat mengidentifikasi hukum Iqlab dengan tepat.",
        scoreWeight: 2,
      },
      {
        id: "q2",
        number: 2,
        type: "pg_kompleks",
        stimulus: "Di bawah ini adalah beberapa contoh bacaan tajwid dalam Al-Qur'an.",
        questionText: "Pilihlah Benar atau Salah untuk setiap pernyataan mengenai hukum Nun Sukun/Tanwin berikut:",
        complexSubItems: [
          { statement: "Lafaz ﴿مَنْ يَّعْمَلْ﴾ mengandung hukum bacaan Idgham Bighunnah.", isTrue: true },
          { statement: "Lafaz ﴿مِنْ خَوْفٍ﴾ dibaca dengung karena merupakan hukum Ikhfa'.", isTrue: false },
          { statement: "Lafaz ﴿مِنْ رَّبِّهِمْ﴾ dibaca Idgham Bilaghunnah tanpa suara dengung.", isTrue: true },
        ],
        answerKey: "Pernyataan 1: BENAR, Pernyataan 2: SALAH (Izhar Halqi), Pernyataan 3: BENAR",
        explanation: "1. Nun sukun bertemu Ya dibaca Idgham Bighunnah (Benar).\n2. Nun sukun bertemu Kha dibaca Izhar Halqi tanpa dengung (Salah).\n3. Nun sukun bertemu Ra dibaca Idgham Bilaghunnah (Benar).",
        bloomLevel: "C4 (HOTS)",
        cpElement: "Analisis Tajwid Kompleks",
        indikatorSoal: "Siswa menganalisis kebenaran 3 pernyataan hukum Tajwid.",
        scoreWeight: 3,
      },
      {
        id: "q3",
        number: 3,
        type: "menjodohkan",
        stimulus: "Jodohkan istilah Tajwid berikut dengan penjelasan makhraj atau artinya yang tepat:",
        questionText: "Jodohkan Kolom A (Istilah Tajwid) dengan Kolom B (Keterangan Hukum):",
        matchingPairs: [
          { left: "1. Izhar Halqi", right: "A. Membaca jelas tanpa dengung pada 6 huruf tenggorokan" },
          { left: "2. Idgham Bighunnah", right: "B. Memasukkan suara ke huruf berikutnya disertai dengung (Y-N-M-W)" },
          { left: "3. Ikhfa' Haqiqi", right: "C. Membaca samar antara izhar dan idgham disertai dengung" },
        ],
        answerKey: "1-A, 2-B, 3-C",
        explanation: "Setiap istilah berpasangan secara tepat dengan definisi hukum makhrajnya.",
        bloomLevel: "C3 (MOTS)",
        cpElement: "Makhraj & Tajwid",
        indikatorSoal: "Siswa menjodohkan istilah tajwid dengan definisi tepat.",
        scoreWeight: 3,
      },
      {
        id: "q4",
        number: 4,
        type: "isian_singkat",
        questionText: "Lanjutan dari QS. Al-A'la ayat 1: ﴿سَبِّحِ اسْمَ رَبِّكَ الْأَعْلَى﴾, ayat yang berikutnya adalah ﴿الَّذِي خَلَقَ فَـ ...﴾.",
        answerKey: "فَسَوَّى (Fasawwaa)",
        explanation: "Ayat kedua Surah Al-A'la berbunyi ﴿الَّذِي خَلَقَ فَسَوَّى﴾.",
        bloomLevel: "C1 (LOTS)",
        cpElement: "Hafalan Surah Juz 30",
        indikatorSoal: "Siswa melengkapi ayat Surah Al-A'la dengan benar.",
        scoreWeight: 2,
      },
      {
        id: "q5",
        number: 5,
        type: "uraian",
        stimulus: "Seorang santri membaca QS. Al-Ghasyiyah dan menemukan hukum bacaan Nun Sukun pada kalimat ﴿عَامِلَةٌ نَّاصِبَةٌ﴾ dan ﴿تَصْلَى نَارًا حَامِيَةً﴾.",
        questionText: "Uraikan analisis tajwid lengkap untuk kedua lafaz di atas! Sebutkan nama hukumnya, huruf penyebabnya, dan cara membacanya yang tepat!",
        answerKey: "1) ﴿عَامِلَةٌ نَّاصِبَةٌ﴾: Tanwin Dhommah bertemu huruf Nun (ن). Hukumnya Idgham Bighunnah. Cara membaca: Tanwin dimasukkan ke huruf Nun dengan suara dengung 2 harakat.\n2) ﴿نَارًا حَامِيَةً﴾: Tanwin Fathah bertemu huruf Ha (ح). Hukumnya Izhar Halqi. Cara membaca: Tanwin dibaca jelas/terang tanpa dengung.",
        explanation: "Penjelasan mencakup nama hukum, huruf pembentuk, serta kaidah pengucapan yang shahih.",
        rubric: "Skor 5: Analisis lengkap & tepat untuk kedua lafaz.\nSkor 3: Hanya tepat 1 lafaz atau penjelasan kurang harakat.\nSkor 1: Menjawab tapi hukum salah.",
        bloomLevel: "C5 (HOTS)",
        cpElement: "Penerapan Tajwid Praktis",
        indikatorSoal: "Siswa menguraikan analisis hukum tajwid pada 2 frasa Al-Qur'an secara sistematis.",
        scoreWeight: 5,
      },
    ],
    kisiKisiMatrix: [
      { nomorSoal: 1, cpElement: "Tajwid Nun Sukun", materi: "Hukum Iqlab", indikatorSoal: "Mengidentifikasi hukum Iqlab dalam potongan ayat", bentukSoal: "Pilihan Ganda", levelKognitif: "C2 (MOTS)" },
      { nomorSoal: 2, cpElement: "Tajwid Nun Sukun", materi: "Idgham & Izhar", indikatorSoal: "Menganalisis 3 pernyataan hukum Tajwid", bentukSoal: "PG Kompleks", levelKognitif: "C4 (HOTS)" },
      { nomorSoal: 3, cpElement: "Tajwid Nun Sukun", materi: "Definisi Hukum Tajwid", indikatorSoal: "Menjodohkan istilah dengan definisi hukum", bentukSoal: "Menjodohkan", levelKognitif: "C3 (MOTS)" },
      { nomorSoal: 4, cpElement: "Hafalan Juz 30", materi: "QS. Al-A'la", indikatorSoal: "Melengkapi sambungan ayat QS. Al-A'la", bentukSoal: "Isian Singkat", levelKognitif: "C1 (LOTS)" },
      { nomorSoal: 5, cpElement: "Tajwid Praktis", materi: "Analisis Lafaz Al-Qur'an", indikatorSoal: "Menguraikan analisis tajwid secara terinci", bentukSoal: "Uraian", levelKognitif: "C5 (HOTS)" },
    ],
  },
  {
    id: "sample-sma-01",
    title: "Sumatif Akhir Semester (SAS) Fisika - Terapan Pesantren & Teknologi",
    institution: "SMA Plus Al-Hamidy",
    grade: "Kelas 10",
    subject: "Fisika (Fase E)",
    assessmentType: "Summative",
    semester: "Ganjil",
    academicYear: "2025/2026",
    timeLimitMinutes: 90,
    generalInstructions: [
      "Berdoalah sebelum mengerjakan soal.",
      "Tuliskan identitas Anda secara lengkap dan benar.",
      "Jawablah soal-soal hitungan lengkap dengan rumus dan satuan yang jelas.",
      "Gunakan kalkulator dasar jika diperlukan, dilarang membuka smartphone.",
    ],
    summaryCP: "Peserta didik mampu menerapkan konsep Vektor, Kinematika Gerak Lurus, dan Hukum Newton dalam menyelesaikan permasalahan fisika kontekstual.",
    summaryTP: "Menganalisis hubungan antara gaya, massa, dan percepatan (Hukum II Newton) pada sistem mekanika sederhana.",
    kopConfig: DEFAULT_KOP_SMA,
    sigConfig: DEFAULT_SIG_SMA,
    createdAt: "2026-07-22T09:00:00Z",
    updatedAt: "2026-07-22T09:00:00Z",
    questions: [
      {
        id: "q1_sma",
        number: 1,
        type: "pilihan_ganda",
        stimulus: "Sebuah pompa air di kompleks SMA Plus Al-Hamidy menarik air dari sumur bor sejauh 15 meter secara vertikal dengan kecepatan konstan.",
        questionText: "Jika massa air yang dipindahkan adalah 200 kg dan percepatan gravitasi g = 10 m/s², berapakah usaha yang dilakukan oleh pompa tersebut?",
        options: [
          "A. 1.500 Joule",
          "B. 3.000 Joule",
          "C. 15.000 Joule",
          "D. 30.000 Joule",
          "E. 300.000 Joule",
        ],
        answerKey: "D. 30.000 Joule",
        explanation: "Usaha W = m x g x h = 200 kg x 10 m/s² x 15 m = 30.000 Joule.",
        bloomLevel: "C3 (MOTS)",
        cpElement: "Usaha dan Energi",
        indikatorSoal: "Siswa menghitung besar usaha perubahan posisi air menggunakan rumus W = m.g.h.",
        scoreWeight: 2,
      },
      {
        id: "q2_sma",
        number: 2,
        type: "uraian",
        stimulus: "Siswa SMA Plus Al-Hamidy merancang proyek pembuatan pengangkat barang sederhana berbasis katrol tunggal bergerak untuk mengangkat beras seberat 100 kg ke lantai 2 asrama.",
        questionText: "a) Gambarkan skema gaya (Gaya Berat dan Gaya Tarik).\nb) Hitunglah gaya minimal yang diperlukan untuk mengangkat beras tersebut jika katrol dianggap ideal tanpa gesekan (g = 9.8 m/s²)!",
        answerKey: "a) Berat beban W = m x g = 100 kg x 9.8 m/s² = 980 N searah ke bawah. Gaya Tali T1 dan T2 ke atas.\nb) Pada katrol bergerak ideal, Keuntungan Mekanis (KM) = 2. Maka Gaya tarik F = W / 2 = 980 N / 2 = 490 N.",
        explanation: "Katrol bergerak membagi beban menjadi dua tali pendukung sehingga gaya tarik cukup setengah dari gaya berat total.",
        rubric: "Skor 5: Gambar gaya benar & perhitungan gaya F = 490 N tepat dengan satuan.\nSkor 3: Perhitungan benar tanpa skema gaya.\nSkor 1: Hanya menuliskkan rumus tanpa penyelesaian.",
        bloomLevel: "C4 (HOTS)",
        cpElement: "Pesawat Sederhana & Hukum Newton",
        indikatorSoal: "Siswa menganalisis gaya mekanis pada katrol bergerak kontekstual.",
        scoreWeight: 5,
      },
    ],
    kisiKisiMatrix: [
      { nomorSoal: 1, cpElement: "Usaha dan Energi", materi: "Usaha Gravitasi", indikatorSoal: "Menghitung usaha pompa air sumur bor", bentukSoal: "Pilihan Ganda", levelKognitif: "C3 (MOTS)" },
      { nomorSoal: 2, cpElement: "Hukum Newton & Katrol", materi: "Keuntungan Mekanis", indikatorSoal: "Menganalisis gaya katrol bergerak beras asrama", bentukSoal: "Uraian", levelKognitif: "C4 (HOTS)" },
    ],
  },
];
